### Numpy array operations

In [2]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print('Basics slicing: ',arr[2:7])
print('basic step: ', arr[1:9:2])
print('negative indexing: ', arr[-2])

Basics slicing:  [3 4 5 6 7]
basic step:  [2 4 6 8]
negative indexing:  9


In [13]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print('specific element: ',arr_2d[1,2])
print('entire row: ', arr_2d[1])
print('entire column: ', arr_2d[:,1])

specific element:  6
entire row:  [4 5 6]
entire column:  [2 5 8]


## sorting

In [18]:
unsorted = np.array([3,5,1,2,7,6,8,10,9])
print('sorted array', np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print('sorted 2d array by column: ', np.sort(arr_2d_unsorted,axis=0))
print('sorted 2d array by row: ', np.sort(arr_2d_unsorted,axis=1))

sorted array [ 1  2  3  5  6  7  8  9 10]
sorted 2d array by column:  [[1 1]
 [2 2]
 [3 3]]
sorted 2d array by row:  [[1 3]
 [1 2]
 [2 3]]


## Filter

In [6]:
numbers  = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = numbers[numbers % 2 == 0]
print('Even numbers: ', even_num)

Even numbers:  [ 2  4  6  8 10]


## Filter with mask

In [8]:
mask = numbers > 5
print('Numbers greater than 5 ', numbers[mask])

Numbers greater than 5  [ 6  7  8  9 10]


## Fancy indexing and np.where()

In [13]:
indices = [0, 2, 4]
print(numbers[indices])

where_results = np.where(numbers > 5)
print(where_results)
print('NP where ',numbers[where_results])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where  [ 6  7  8  9 10]


In [18]:
condition_array1 = np.where(numbers > 5, numbers*2, numbers)
condition_array2 = np.where(numbers > 5, 'True', 'False')
print(condition_array1)
print(condition_array2)

[ 1  2  3  4  5 12 14 16 18 20]
['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


## Adding and removing data

In [24]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
# it simply add values of arrays
combined_array = arr1 + arr2
print('combined array: ',combined_array)
# it simply combine two arrays in single array
combine = np.concatenate((arr1,arr2))
print(combine)

combined array:  [ 6  8 10 12]
[1 2 3 4 5 6 7 8]


## Array compatibility

In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,10])

print('Compability shapes',a.shape == b.shape)
print('Compability shapes',a.shape == c.shape)

Compability shapes True
Compability shapes False


In [39]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
# this will add new row in to original row
with_newrow = np.vstack((original,new_row))

print('original array\n',original)
print('with new row\n',with_newrow)

new_col = np.array([[7],[8]])
with_newcol = np.hstack((original,new_col))
print('with new column\n',with_newcol)

original array
 [[1 2]
 [3 4]]
with new row
 [[1 2]
 [3 4]
 [5 6]]
with new column
 [[1 2 7]
 [3 4 8]]


In [41]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print('array after deletion: ',deleted)

array after deletion:  [1 2 4 5]
