## Numpy array and basics

In [5]:
import numpy as np

## creating array from list

In [2]:
arr_1d = np.array([1,2,3,4])
print("1D array: ", arr_1d)
arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array: ", arr_2d)

1D array:  [1 2 3 4]
2d array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [8]:
py_list = [1,2,3]
print("python list multiplication ", py_list * 2)

np_array = np.array([1,2,3])
print("python array multiplication ", np_array * 2)


import time

start = time.time()
py_list = [i*2 for i in range(100000000)]
print('/n list operation time: ', time.time() - start)

start = time.time()
np_array = np.arange(100000000) * 2
print('/n numpy array operation time: ', time.time() - start)


python list multiplication  [1, 2, 3, 1, 2, 3]
python array multiplication  [2 4 6]
/n list operation time:  4.322539329528809
/n numpy array operation time:  0.5452303886413574


### Creating array from scratch

In [ ]:
zeros = np.zeros((3,4))
print('zeros array:\n',zeros)

ones = np.ones((2,3))
print('one array:\n', ones)

full = np.full((2,2),7)
print('Full array:\n',full)

random = np.random.random((2,2))
print('random array:\n',random)

sequence = np.arange(0,10,2)
print('sequence array:\n',sequence)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array:
 [[7 7]
 [7 7]]
random array:
 [[0.05046171 0.94968977]
 [0.99124804 0.77384372]]
sequence array:
 [0 2 4 6 8]


### Vector, Matrix, Tensor

In [14]:
vector = np.array([1,2,3])
print('vector array: \n',vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print('matrix array: \n',matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print('tensor array:\n ', tensor)

vector array: 
 [1 2 3]
matrix array: 
 [[1 2 3]
 [4 5 6]]
tensor array:
  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])
print('Shape: ',arr.shape)
print('Dimension: ',arr.ndim)
print('Size: ',arr.size)
print('Dtype: ',arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
Dtype:  int64


### Array reshaping

In [7]:
arr = np.arange(12)

reshaped = arr.reshape((3,4))
print('reshaped array: \n',reshaped)

# flatten return copy
flattend = reshaped.flatten()
print('Flattend array:\n',flattend)

#ravel (returns view, instead of copy)
ravelled = flattend.ravel()
print('ravelled array:\n',ravelled)

# Transpose
transpose = reshaped.T 
print('Transpose array: \n', transpose)

reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattend array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravelled array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
